# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Gradle

on: [push, pull_request]

jobs:
  deb:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
        with:
          fetch-depth: 0
      - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - run: git describe --match "Jitsi-[0-9\.]*" --long --dirty --always

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1.3.0
        with:
          java-version: 1.8

      - name: Verify Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1.0.3

      - name: Cache Gradle dependencies
        uses: actions/cache@v1.1.2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build x64-deb
        env:
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.GPG_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.GPG_PW }}
        run: ./gradlew bundles signDeb -Papplication.target=x64
      - name: Upload x64-deb
        uses: actions/upload-artifact@v1
        with:
          name: jitsi-debian-x64
          path: build/distributions/

      - name: Build x86-deb
        env:
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.GPG_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.GPG_PW }}
        run: |
          rm -rf build/
          ./gradlew bundles signDeb -Papplication.target=x86
      - name: Upload x86-deb
        uses: actions/upload-artifact@v1
        with:
          name: jitsi-debian-x86
          path: build/distributions/

  wix:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2.1.0
        with:
          fetch-depth: 0
      - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1.3.0
        with:
          java-version: 1.8

      - name: Verify Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1.0.3

      - name: Cache Gradle dependencies
        uses: actions/cache@v1.1.2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build x64
        run: |
          cd $Env:GITHUB_WORKSPACE/native/windows
          cmake -B cmake-build-x64 -A x64
          cmake --build cmake-build-x64 --config Release
          cd $Env:GITHUB_WORKSPACE
          & .\gradlew --% bundles wixLight -Papplication.target=x64
      - name: Upload msi
        uses: actions/upload-artifact@v1
        with:
          name: jitsi-win-x64
          path: build/install/wix/setup.msi

      - name: Build x86
        run: |
          cd $Env:GITHUB_WORKSPACE
          ./gradlew clean
          cd $Env:GITHUB_WORKSPACE/native/windows
          cmake -B cmake-build-x86 -A Win32
          cmake --build cmake-build-x86 --config Release
          cd $Env:GITHUB_WORKSPACE
          & .\gradlew --% bundles signMsi -Papplication.target=x86
      - name: Upload msi
        uses: actions/upload-artifact@v1
        with:
          name: jitsi-win-x86
          path: build/install/wix/setup.msi

  mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2.1.0
        with:
          fetch-depth: 0
      - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1.3.0
        with:
          java-version: 1.8

      - name: Verify Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1.0.3

      - name: Cache Gradle dependencies
        uses: actions/cache@v1.1.2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build natives
        run: |
          cd $GITHUB_WORKSPACE/native/macosx
          cmake -B cmake-build
          cmake --build cmake-build --config Release --verbose

      - name: Build with Gradle
        run: ./gradlew bundles createDmg

      - name: Upload dmg
        uses: actions/upload-artifact@v1
        with:
          name: jitsi-mac
          path: build/install/jitsi.dmg
